import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import css from "rollup-plugin-css-only";

import { pluginDestination } from "./dev-config";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

const output = [
  {
    input: "./src/main.ts",
    output: {
      dir: ".",
      sourcemap: "inline",
      format: "cjs",
      exports: "default",
      banner,
    },
    external: ["obsidian"],
    plugins: [
      css({ output: "styles.css" }),
      typescript(),
      nodeResolve({ browser: true }),
      commonjs(),
    ],
  },
];

if (pluginDestination) {
  output.push({
    input: "./src/main.ts",
    output: {
      dir: pluginDestination,
      sourcemap: "inline",
      format: "cjs",
      exports: "default",
      banner,
    },
    external: ["obsidian"],
    plugins: [
      css({ output: "styles.css" }),
      typescript(),
      nodeResolve({ browser: true }),
      commonjs(),
    ],
  });
}

export default output;
